### ISSUE TITLE
comentarios avances 2

### ISSUE THREAD

**Issue by AliciaMstt** [DelilChincoya/ProyectoFinalBioinf2017-I#1]
"Hasta el momento no he podido ensamblar más de 30,000 pb" ¿Sabes el motivo? Me gustaría que me detalles más para asegurarnos que no te atores después. 

En tu trabajo final no olvides poner las referencias de los software que estás ocupando.

**Comment by DelilChincoya** [comment]
Es probablemente por la secuencia que utilicé como semilla; actualmente ya pude ensamblar aprox. 76,000 pb. Para ello, de mis lecturas extraje la secuencia de RuBP  completa y  la utilicé como semilla (RuBP es la secuencia que recomienda NOVOPlasty), pero otra vez estoy estancada ahí. Creo que debo de comenzar a explorar otros softwares.

**Comment by AliciaMstt** [comment]
Revisa ayuda en internet, quizá en Biostars  puede haber info.
